SELECT * FROM COMMUNITY_BOARD;
UPDATE COMMUNITY_BOARD SET COMMUNITY_FAVORITE ='푸들', COMMUNITY_CONTENT='푸들푸들', COMMUNITY_FILE='DOG3.jpg' WHERE COMMUNITY_NUM=4;
DELETE FROM COMMUNITY_BOARD;
CREATE SEQUENCE C_SEQ START WITH 1 INCREMENT BY 1;
DROP SEQUENCE C_SEQ;


CREATE TABLE COMMENT_BOARD(
COMMENT_NUM NUMBER PRIMARY KEY, --댓글 글번호
COMMENT_ID VARCHAR2(20) NOT NULL, --댓글 작성자
COMMENT_DATE DATE NOT NULL, --댓글 작성일
COMMENT_PARENT NUMBER NOT NULL, --부모글
COMMENT_CONTENT VARCHAR2(4000) NOT NULL ); --내용.
CREATE SEQUENCE CO_SEQ START WITH 1 INCREMENT BY 1; --코멘트 시퀀스

drop table comment_board;